In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import LabelEncoder#for train test splitting
from sklearn.model_selection import train_test_split#for decision tree object
from sklearn.tree import DecisionTreeClassifier#for checking testing results
from sklearn.metrics import classification_report, confusion_matrix#for visualizing tree 
from sklearn.tree import plot_tree

In [2]:
# loading data 
data = pd.read_csv("Fraud_check.csv")
data.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Undergrad        600 non-null    object
 1   Marital.Status   600 non-null    object
 2   Taxable.Income   600 non-null    int64 
 3   City.Population  600 non-null    int64 
 4   Work.Experience  600 non-null    int64 
 5   Urban            600 non-null    object
dtypes: int64(3), object(3)
memory usage: 28.2+ KB


In [4]:
data.shape

(600, 6)

In [5]:
data.describe

<bound method NDFrame.describe of     Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..         

In [6]:
data.isnull().any()

Undergrad          False
Marital.Status     False
Taxable.Income     False
City.Population    False
Work.Experience    False
Urban              False
dtype: bool

In [7]:
data.loc[data['Taxable.Income'] <=30000,'Taxable_Income']= 'Risky'
data.loc[data['Taxable.Income'] >30000,'Taxable_Income']= 'Good'

In [8]:
data.head(2)

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   

  Urban Taxable_Income  
0   YES           Good  
1   YES           Good

In [9]:
data.drop('Taxable.Income',1,inplace=True)

C:\Users\myself\AppData\Local\Temp\ipykernel_9992\2031450657.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  data.drop('Taxable.Income',1,inplace=True)


In [10]:
data['Marital.Status'].value_counts()

Single      217
Married     194
Divorced    189
Name: Marital.Status, dtype: int64

In [11]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
data['Marital.Status']= label_encoder.fit_transform(data['Marital.Status']) 
data['Marital.Status'].unique()

array([2, 0, 1])

In [12]:
data.head(2)

Undergrad  Marital.Status  City.Population  Work.Experience Urban  \
0        NO               2            50047               10   YES   
1       YES               0           134075               18   YES   

  Taxable_Income  
0           Good  
1           Good

In [13]:
data.Undergrad.value_counts()

YES    312
NO     288
Name: Undergrad, dtype: int64

In [14]:
data['Undergrad']= label_encoder.fit_transform(data['Undergrad']) 
data['Undergrad'].unique()

array([0, 1])

In [15]:
data.Urban.value_counts()

YES    302
NO     298
Name: Urban, dtype: int64

In [16]:
data['Urban']= label_encoder.fit_transform(data['Urban']) 
data['Urban'].unique() 

array([1, 0])

In [17]:
data.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0          0               2            50047               10      1   
1          1               0           134075               18      1   
2          0               1           160205               30      1   
3          1               2           193264               15      1   
4          0               1            27533               28      0   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [18]:
colnames = list(data.columns)
predictors = colnames[0:5]
target = colnames[5]

In [19]:
predictors

['Undergrad', 'Marital.Status', 'City.Population', 'Work.Experience', 'Urban']

In [20]:
target

'Taxable_Income'

In [21]:
X = data[predictors]
Y = data[target]

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [23]:
data.head()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0          0               2            50047               10      1   
1          1               0           134075               18      1   
2          0               1           160205               30      1   
3          1               2           193264               15      1   
4          0               1            27533               28      0   

  Taxable_Income  
0           Good  
1           Good  
2           Good  
3           Good  
4           Good

In [24]:
data['rf_pred'] = rf.predict(X)

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data['Taxable_Income'],data['rf_pred'])

array([[476,   0],
       [  0, 124]], dtype=int64)